title: Zhanchi Wang
url: https://ZhanchiWang.github.io
baseurl: ""
exclude:
  - _pages
  - _posts
  - _portfolio
  - _drafts
  - scripts
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - Dockerfile
  - docker-compose.yaml
  - .devcontainer
  - vendor
  - node_modules
  - assets/css/main.scss
  - publications-source.json
  - scholar-source.tmp
  - scholar-detail.tmp
